window.WEDDING_DATA = {
    defaultProfile: "groom",
    sections: {
        petals: true,
        music: true,
        quickNav: true,
        invitationLetter: true,
        countdown: true,
        couple: true,
        story: false,
        events: true,
        maps: true,
        gallery: true,
        video: false,
        gift: false,
        rsvp: false,
        guestbook: false,
        footer: true,
    },
    profiles: {
        groom: {
            label: "Nhà trai",
            side: "groom",
            site: {
                title: "Thiệp Cưới Nhà Trai | Xuân Dương & Bích Nga",
            },
            cover: {
                // note: "Phiên bản thiệp mời dành cho phía nhà trai. Khi deploy riêng, hãy dùng link nha-trai.html hoặc ?profile=groom.",
            },
            media: {
                coverImage: "./assets/images/highlights/slide-01.webp",
                coverPosition: "35% 20%",
                heroImage: "./assets/images/albums/blend/blend-17.webp",
                heroPosition: "35% 20%",
                footerImage: "./assets/images/highlights/slide-04.webp",
            },
            wedding: {
                solarDateLong: "Thứ Hai, 01 tháng 06 năm 2026",
                solarDateShort: "01.06.2026",
                lunarDate: "Nhằm ngày 16 tháng 04 năm Bính Ngọ",
                countdownISO: "2026-06-01T09:00:00+07:00",
                city: "Tư gia nhà trai • Thôn 5 - Xã Ea Ô - Tỉnh Đắk Lắk",
                guestArrivalTime: "10:30",
                ceremonyTime: "11:00",
                footerText: `Thiệp mời phía nhà trai \n• Xuân Dương & Bích Nga \n• 01.06.2026`,
            },
            sections: {
                countdown: true,
                events: true,
                maps: true,
                gallery: true,
                gift: true,
            },
            heroIntro: "Gia đình nhà trai trân trọng kính mời",
            heroMeta: [
                { label: "Ngày tổ chức", value: "01.06.2026" },
                { label: "Lễ tân hôn", value: "09:00" },
                { label: "Đón tiệc", value: "10:30" },
            ],
            peopleOrder: ["groom", "bride"],
            featuredPerson: "groom",
            eventIds: ["groomCeremony", "party"],
            mapEventIds: ["groomCeremony", "party"],
        },
        bride: {
            label: "Nhà gái",
            side: "bride",
            site: {
                title: "Thiệp Cưới Nhà Gái | Xuân Dương & Bích Nga",
            },
            cover: {
                note: "Phiên bản thiệp mời dành cho phía nhà gái. Khi có giờ cử hành chính xác bên nhà gái, chỉ cần cập nhật trong profile bride.",
            },
            media: {
                coverImage: "./assets/images/profiles/bride-profile.webp",
                coverPosition: "42% 58%",
                heroImage: "./assets/images/profiles/bride-profile.webp",
                heroPosition: "42% 58%",
                footerImage: "./assets/images/highlights/slide-05.webp",
            },
            wedding: {
                solarDateLong: "Thông tin lễ bên nhà gái",
                solarDateShort: "30.05.2026",
                lunarDate:
                    "Địa điểm nhà gái: Thôn Quảng Cư 2 - Xã Ea Kar - Tỉnh Đắk Lắk",
                countdownISO: "",
                city: "Tư gia nhà gái • Thôn Quảng Cư 2 - Xã Ea Kar - Tỉnh Đắk Lắk",
                guestArrivalTime: "10:30",
                ceremonyTime: "11:00",
                footerText: "Thiệp mời phía nhà gái • Xuân Dương & Bích Nga",
            },
            sections: {
                countdown: false,
                events: true,
                maps: true,
                gallery: true,
                gift: true,
            },
            heroIntro: "Gia đình nhà gái trân trọng kính mời",
            heroMeta: [
                { label: "Bên mời", value: "Nhà gái" },
                { label: "Địa điểm", value: "Thôn Quảng Cư 2 - Xã Ea Kar" },
                { label: "Đón tiệc", value: "10:30" },
            ],
            peopleOrder: ["bride", "groom"],
            featuredPerson: "bride",
            eventIds: ["brideCeremony"],
            mapEventIds: ["brideCeremony"],
        },
    },
    site: {
        title: "Thiệp Cưới Online | Bích Nga & Xuân Dương",
        description:
            "Thiệp cưới online phong cách Việt Nam với đầy đủ thông tin lễ cưới, bản đồ, album, RSVP và lời chúc.",
        guestDefaultName: "Anh/Chị & Gia đình",
    },
    cover: {
        eyebrow: "Trân trọng kính mời",
        openButtonLabel: "Mở thiệp",
        invitationText:
            "Trân trọng kính mời Quý khách cùng gia đình đến chung vui trong ngày thành hôn của chúng tôi.",
        note: "Mời Quý khách mở thiệp, phần hồi hộp xin nhường lại cho cô dâu chú rể.",
    },
    wedding: {
        solarDateLong: "Thứ Hai, 01 tháng 06 năm 2026",
        solarDateShort: "01.06.2026",
        lunarDate: "Nhằm ngày 16 tháng 04 năm Bính Ngọ",
        countdownISO: "2026-06-01T09:00:00+07:00",
        city: "Thôn 5 - Xã Ea Ô - Tỉnh Đắk Lắk",
        guestArrivalTime: "10:30",
        ceremonyTime: "11:00",
        invitationEyebrow: "Lời mời chính thức",
        invitationHeading: "Trân trọng kính mời",
        invitationBody:
            "Sự hiện diện của Quý khách là niềm vinh hạnh lớn đối với gia đình chúng tôi.",
        invitationSign: "Gia đình chúng tôi hân hạnh được đón tiếp.",
        giftIntro:
            "Trong trường hợp Quý khách muốn gửi thêm lời chúc đến cô dâu chú rể theo một cách riêng, vui lòng nhấn nút bên dưới để xem thông tin.",
        footerEyebrow: "Trân quý",
        footerHeading: "Cảm ơn Quý khách đã dành thời gian xem thiệp mời",
        footerText:
            "Xuân Dương & Bích Nga • 01.06.2026 • Hân hạnh được đón tiếp Quý khách",
    },
    media: {
        coverImage: "./assets/images/highlights/slide-01.webp",
        coverPosition: "50% 84%",
        heroImage: "./assets/images/highlights/slide-02.webp",
        heroPosition: "50% 82%",
        footerImage: "./assets/images/highlights/slide-04.webp",
        musicSrc: "./assets/music/background-music.mp3",
        videoSrc: "./assets/video/wedding-highlight.mp4",
        videoPoster: "./assets/images/highlights/slide-03.webp",
        videoEmbedUrl: "",
        videoPlaceholderTitle: "Thêm video highlight của bạn tại đây",
        videoPlaceholderNote:
            "Đặt file video vào assets/video/wedding-highlight.mp4 hoặc dùng videoEmbedUrl.",
    },
    couple: {
        groom: {
            roleLabel: "Chú rể",
            shortName: "Xuân Dương",
            fullName: "Xuân Dương",
            birthYear: "",
            job: "",
            father: "",
            mother: "",
            address: "Thôn 5 - Xã Ea Ô - Tỉnh Đắk Lắk",
            quote: "",
            image: "./assets/images/profiles/groom-profile.webp",
            imageAlt: "Thông tin chú rể",
            imagePosition: "35% 18%",
            gift: {
                enabled: true,
                title: "Gửi lời chúc tới chú rể",
                bankName: "VPBank",
                accountNumber: "178185338",
                accountName: "HA XUAN DUONG",
                qrLabel: "QR chú rể",
                qrImage: "./assets/images/qr/groom-qr-clean.png",
                qrCardImage: "./assets/images/qr/groom-qr-card.jpg",
                note: "Xin chân thành cảm ơn tấm lòng và tình cảm Quý khách đã dành cho chú rể.",
            },
        },
        bride: {
            roleLabel: "Cô dâu",
            shortName: "Bích Nga",
            fullName: "Bích Nga",
            birthYear: "",
            job: "",
            father: "",
            mother: "",
            address: "Thôn Quảng Cư 2 - Xã Ea Kar - Tỉnh Đắk Lắk",
            quote: "",
            image: "./assets/images/profiles/bride-profile.webp",
            imageAlt: "Thông tin cô dâu",
            imagePosition: "42% 58%",
            gift: {
                enabled: true,
                title: "Gửi lời chúc tới cô dâu",
                bankName: "VietinBank",
                accountNumber: "104882875540",
                accountName: "CHU THI BICH NGA",
                qrLabel: "QR cô dâu",
                qrImage: "./assets/images/qr/bride-qr-clean.png",
                qrCardImage: "./assets/images/qr/bride-qr-card.jpg",
                note: "Xin chân thành cảm ơn tấm lòng và tình cảm Quý khách đã dành cho cô dâu.",
            },
        },
    },
    story: [
        {
            date: "Từ lời chào đầu tiên",
            title: "Mở đầu thật dịu dàng",
            description:
                "Mỗi tấm ảnh là một lát cắt rất thật của hành trình chúng tôi đi cùng nhau, bắt đầu bằng những lần trò chuyện tưởng chừng rất bình thường nhưng lại hóa ra đặc biệt.",
            image: "./assets/images/highlights/slide-01.webp",
            imageAlt: "Khoảnh khắc nổi bật 1",
        },
        {
            date: "Khi tình yêu đủ đầy",
            title: "Bình yên là có nhau",
            description:
                "Chúng tôi học cách yêu thương, lắng nghe và ở cạnh nhau qua những ngày vui lẫn những ngày bận rộn. May mắn là đến giờ vẫn còn rất hợp ý, kể cả lúc chọn món ăn.",
            image: "./assets/images/highlights/slide-02.webp",
            imageAlt: "Khoảnh khắc nổi bật 2",
        },
        {
            date: "Ngày quyết định",
            title: "Chính thức về chung một nhà",
            description:
                "Sau nhiều lần nghiêm túc bàn chuyện tương lai, xen giữa vài cuộc đối thoại kiểu “ăn gì cũng được”, chúng tôi quyết định cùng nhau bước đến hôn nhân.",
            image: "./assets/images/highlights/slide-03.webp",
            imageAlt: "Khoảnh khắc nổi bật 3",
        },
        {
            date: "Ngày vui sắp tới",
            title: "Hẹn gặp trong niềm hân hoan",
            description:
                "Sự hiện diện của Quý khách sẽ là món quà quý giá để ngày vui của chúng tôi thêm trọn vẹn, ấm áp và nhiều tiếng cười.",
            image: "./assets/images/highlights/slide-04.webp",
            imageAlt: "Khoảnh khắc nổi bật 4",
        },
    ],
    events: [
        {
            id: "groomCeremony",
            tag: "Lễ tân hôn",
            title: "Tư gia nhà trai",
            datetime:
                "Cử hành vào lúc 09:00, Thứ Hai, ngày 01 tháng 06 năm 2026",
            address: "Thôn 5 - Xã Ea Ô - Tỉnh Đắk Lắk",
            mapLabel: "Map lễ tân hôn",
            lat: "12.71147",
            lng: "108.4609",
            mapQuery: "Thôn 5 Xa Ea O, Dak Lak",
            highlight: false,
        },
        {
            id: "party",
            tag: "Tiệc cưới",
            title: "Tư gia nhà trai",
            datetime:
                "Đón khách: 10:30 • Khai tiệc: 11:00 • Thứ Hai, 01 tháng 06 năm 2026",
            address: "Thôn 5 - Xã Ea Ô - Tỉnh Đắk Lắk",
            mapLabel: "Map tiệc cưới",
            lat: "12.71147",
            lng: "108.4609",
            mapQuery: "Thôn 5 Xa Ea O, Dak Lak",
            highlight: true,
        },
        {
            id: "brideCeremony",
            tag: "Lễ bên nhà gái",
            title: "Tư gia nhà gái",
            datetime:
                "Đón khách: 10:30 • Khai tiệc: 11:00 • Thứ Bảy, 30 tháng 05 năm 2026",
            address: "Thôn Quảng Cư 2 - Xã Ea Kar - Tỉnh Đắk Lắk",
            mapLabel: "Map nhà gái",
            lat: "12.7490473",
            lng: "108.4997893",
            mapQuery: "Thôn Quang Cu 2 Xa Ea Kar, Dak Lak",
            highlight: false,
        },
    ],
    gallery: {
        highlights: [
            {
                src: "./assets/images/highlights/slide-01.webp",
                alt: "Khoảnh khắc nổi bật 1",
                position: "50% 88%",
            },
            {
                src: "./assets/images/highlights/slide-02.webp",
                alt: "Khoảnh khắc nổi bật 2",
                position: "54% 86%",
            },
            {
                src: "./assets/images/highlights/slide-03.webp",
                alt: "Khoảnh khắc nổi bật 3",
                position: "55% 78%",
            },
            {
                src: "./assets/images/highlights/slide-04.webp",
                alt: "Khoảnh khắc nổi bật 4",
                position: "50% 82%",
            },
            {
                src: "./assets/images/highlights/slide-05.webp",
                alt: "Khoảnh khắc nổi bật 5",
                position: "50% 42%",
            },
        ],
        albums: [
            {
                key: "blend",
                title: "Album ngoại cảnh",
                description:
                    "Những khung hình ngoài trời được sắp lại theo đúng thứ tự để Quý khách xem trọn vẹn hành trình ảnh cưới của chúng tôi.",
                prefix: "./assets/images/albums/blend/blend-",
                count: 18,
                ext: ".webp",
            },
            {
                key: "aqua",
                title: "Album Aqua",
                description:
                    "Bộ ảnh được ghi lại tại Aqua City, nơi những con đường xanh mát và không gian yên bình đã lưu giữ rất nhiều khoảnh khắc dịu dàng. Ảnh đẹp là nhờ nhiếp ảnh gia, còn vẻ tự nhiên là nhờ chúng tôi đã kịp quen với ống kính.",
                prefix: "./assets/images/albums/aqua/aqua-",
                count: 11,
                ext: ".webp",
            },
        ],
    },
    sampleWishes: [
        {
            name: "Chị Mai Anh",
            message:
                "Chúc hai em trăm năm hạnh phúc, luôn yêu thương, sẻ chia và đồng hành cùng nhau trong mọi chặng đường.",
        },
        {
            name: "Anh Hoàng Nam",
            message:
                "Chúc ngày vui của hai bạn thật trọn vẹn, ấm áp và ngập tràn tiếng cười từ đầu buổi đến tận lúc ra về.",
        },
    ],
};
